# Generated by Django 5.0.7 on 2024-08-02 03:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='id',
            field=models.CharField(default=uuid.UUID('bdbc3cf6-53fd-44a1-bc93-b3c648630911'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
    ]
