# Generated by Django 5.0.7 on 2024-08-02 04:21

import auth_app.models
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_usermodel_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usermodel',
            managers=[
                ('all', django.db.models.manager.Manager()),
                ('objects', auth_app.models.VerifyManager()),
            ],
        ),
        migrations.AddField(
            model_name='usermodel',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='id',
            field=models.CharField(default=uuid.UUID('cc13c11b-9cf7-4e4d-bd9c-6160c647f14f'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
    ]
