# Generated by Django 5.0.7 on 2024-08-03 06:35

import auth_app.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_usermodel_managers_usermodel_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usermodel',
            managers=[
                ('all', auth_app.models.AllManager()),
                ('objects', auth_app.models.VerifyManager()),
            ],
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='id',
            field=models.CharField(default=uuid.UUID('f0e7fc13-c4d5-4497-8735-e5865922c9ef'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.CharField(default=uuid.UUID('9f613739-8789-4d74-b460-86f6188ac2b2'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True)),
                ('otp', models.BigIntegerField()),
                ('otp_datetime', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
