# Generated by Django 5.0.7 on 2024-08-05 08:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_usermodel_managers_alter_usermodel_id_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='id',
            field=models.CharField(default=uuid.UUID('ba6d72ad-ed0a-4db4-a579-a2ec220159d3'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='id',
            field=models.CharField(default=uuid.UUID('73402d04-a9be-44c2-b6f0-fa8b0c14ff28'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
    ]
