# Generated by Django 5.0.7 on 2024-08-05 08:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_alter_otp_id_alter_usermodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='id',
            field=models.CharField(default=uuid.UUID('4c168005-836e-41c9-9eb8-e30473444200'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='id',
            field=models.CharField(default=uuid.UUID('5877ecca-0813-4f26-9bc9-86dac38df1d2'), editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
    ]
